// Generated by gencpp from file proj1robot_msgs/ControlInput.msg
// DO NOT EDIT!


#ifndef PROJ1ROBOT_MSGS_MESSAGE_CONTROLINPUT_H
#define PROJ1ROBOT_MSGS_MESSAGE_CONTROLINPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace proj1robot_msgs
{
template <class ContainerAllocator>
struct ControlInput_
{
  typedef ControlInput_<ContainerAllocator> Type;

  ControlInput_()
    : header()
    , forward(0.0)
    , turn(0.0)  {
    }
  ControlInput_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , forward(0.0)
    , turn(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _forward_type;
  _forward_type forward;

   typedef double _turn_type;
  _turn_type turn;





  typedef boost::shared_ptr< ::proj1robot_msgs::ControlInput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::proj1robot_msgs::ControlInput_<ContainerAllocator> const> ConstPtr;

}; // struct ControlInput_

typedef ::proj1robot_msgs::ControlInput_<std::allocator<void> > ControlInput;

typedef boost::shared_ptr< ::proj1robot_msgs::ControlInput > ControlInputPtr;
typedef boost::shared_ptr< ::proj1robot_msgs::ControlInput const> ControlInputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::proj1robot_msgs::ControlInput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::proj1robot_msgs::ControlInput_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::proj1robot_msgs::ControlInput_<ContainerAllocator1> & lhs, const ::proj1robot_msgs::ControlInput_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.forward == rhs.forward &&
    lhs.turn == rhs.turn;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::proj1robot_msgs::ControlInput_<ContainerAllocator1> & lhs, const ::proj1robot_msgs::ControlInput_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace proj1robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::proj1robot_msgs::ControlInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::proj1robot_msgs::ControlInput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::proj1robot_msgs::ControlInput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::proj1robot_msgs::ControlInput_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::proj1robot_msgs::ControlInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::proj1robot_msgs::ControlInput_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::proj1robot_msgs::ControlInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "78975323d29cfab13bfc997e1a08c9e1";
  }

  static const char* value(const ::proj1robot_msgs::ControlInput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x78975323d29cfab1ULL;
  static const uint64_t static_value2 = 0x3bfc997e1a08c9e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::proj1robot_msgs::ControlInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "proj1robot_msgs/ControlInput";
  }

  static const char* value(const ::proj1robot_msgs::ControlInput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::proj1robot_msgs::ControlInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Simple message to communicate intended control. Relayed by middleman.\n"
"\n"
"Header header       # Reference shenanigans\n"
"\n"
"float64 forward     # forward raw control input\n"
"float64 turn        # turn raw control input\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::proj1robot_msgs::ControlInput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::proj1robot_msgs::ControlInput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.forward);
      stream.next(m.turn);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlInput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::proj1robot_msgs::ControlInput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::proj1robot_msgs::ControlInput_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "forward: ";
    Printer<double>::stream(s, indent + "  ", v.forward);
    s << indent << "turn: ";
    Printer<double>::stream(s, indent + "  ", v.turn);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJ1ROBOT_MSGS_MESSAGE_CONTROLINPUT_H
